# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd21c98c7a3329d3b07e915ad2e56710c2a6f3c880810da1afd8c9881a7116e6e258e29bdf22312ed6e79d62bddc93aef12f1272a0de3ac816a03ab4a92730af

test:
  secret_key_base: c1c220240897d4e5dbda3018def91db423098bcadebd7535988c85d7bc50a2671ca220bf57a0bad890cf7892087caa0118efd78bf64bcf264e741da4652a442d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
